[lock]
version = "2"
hub = "https://hub.bend-lang.com"

[tools.bolt]
git = "https://github.com/Emerging-Patterns/bolt"
rev = "ada294e53e151ff1915ffd61cac166d47f38b1a2"
root = "."
narHash = "sha256-/SIF4Mwc7BDn/A4jpDMNud/QTmt1q+tdzFrSdtwN4Wk="
entry = "bolt/main.bend"
